### ISSUE TITLE
Cannot use AutoPersistedBloc

### ISSUE THREAD

**Issue by WahyuSetyawan** [MohiuddinM/no_bloc_flutter#1]
Hello, i'm trying to use this package on my Flutter project, but i encountered this error where the app would throw an error if I use AutoPersistedBloc instead of just Bloc.

The error message is as follows:
```
E/flutter ( 4285): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: 'package:no_bloc/src/persistence_service.dart': Failed assertion: line 43 pos 12: 'directory != null': is not true.
E/flutter ( 4285): #0      _AssertionError._doThrowNew  (dart:core-patch/errors_patch.dart:42:39)
E/flutter ( 4285): #1      _AssertionError._throwNew  (dart:core-patch/errors_patch.dart:38:5)
E/flutter ( 4285): #2      HivePersistenceService._initialize 
package:no_bloc/src/persistence_service.dart:43
E/flutter ( 4285): #3      new HivePersistenceService 
package:no_bloc/src/persistence_service.dart:39
E/flutter ( 4285): #4      new PersistenceService 
package:no_bloc/src/persistence_service.dart:19
```

**Comment by MohiuddinM** [comment]
You have to set the directory where the database will be saved, I have updated the example to show that

https://github.com/MohiuddinM/no_bloc_flutter/blob/b7a566e4c4d44535911c264c92c47fefd61ccd14/example/main.dart#L46

**Comment by WahyuSetyawan** [comment]
Thank you very much, it works.
